            ; Alphabet
            DB LSPC,LSPC,LSPC,LSPC,LSPC
            DB LA,LB,LC,LD,LE,LF,LG,LH,LI,LJ,LL,LN,LO,LP,LR,LS,LT,LU,LY
            DB LDASH
            DB La,Lb,Lc,Ld,Le,Lf,Lg,Lh,Li,Lj,Ll,Ln,Lo,Lp,Lr,Ls,Lt,Lu,Ly
            DB LDASH
            DB L1,L2,L3,L4,L5,L6,L7,L8,L9,L0
            DB LSPC,LSPC,LSPC,LSPC,LSPC,LSPC
            DB DATATERM
